// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateOrderRequest struct {
	UserId    string `json: "userId"`
	ProductId string `json: "productId"`
	Quantity  int    `json: "quantity"`
}

type CreateOrderResponse struct {
	OrderId string `json: "orderId"`
	Message string `json: "message"`
}

type SendSmsRequest struct {
	Phone string `json: "phone"`
}

type SendSmsResponse struct {
	Code string `json: "code"`
}
